import Daggers from './daggers.png'
import Ruby from './ruby.png'
import Solana from './solana.png'
import Deposit from './deposit.png'
import Claim from './claim.png'
import Spin from './spin.png'
import Symbol from './symbol.png'
import MarkBoard from './mark_board.png'
import Fire from './fire.png'
import Arrow from './arrow.png'
import Up from './up.png'
import Down from './down.png'
import Background from './background.png'

export { Daggers, Ruby, Solana, Deposit, Claim, Spin, Symbol, MarkBoard, Fire, Arrow, Up, Down, Background }
